### ISSUE TITLE
Level 2

### ISSUE THREAD

**Issue by rilifon** [uspgamedev/Project-Telos#30]
- [x] Part 1 (Depends on #46)
- [x] Part 2 (Depends on #46)
- [x] Part 3 (Depends on #42 and #55)
- [ ] Boss 2 (Depends on #31)
